openapi: '3.0.2'
info:
  title: Specifications for the services provided by Charmed database operators 
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /users:
    get:
      responses:
        '200':
          description: OK
